### ISSUE TITLE
Big Sur Connectivity Issues

### ISSUE THREAD

**Issue by Exosylver** [misa198/dell-latitude-e5570-hackintosh#11]
I am using a Dell Latitude E5570 i7-6600U HD520 igpu. I connect to the wifi, but it says No Internet. It does not recognize ethernet. What should I do?

**Comment by misa198** [comment]
This EFI for Monterey. 
Replace itlwm in EFI>OC>Kexts with [this](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_BigSur.kext.zip) to use BigSur.

**Comment by Exosylver** [comment]
That’s how I can get Ethernet to work? I tried Monterey and the no Ethernet persists.

**Comment by misa198** [comment]
Reset nvram and try again?
