### ISSUE TITLE
HDMI not working

### ISSUE THREAD

**Issue by job1234** [misa198/dell-latitude-e5570-hackintosh#3]
Hi,
I've updated my laptop from my own opencore config to yours so I was able to update succesfully to MacOS Monterey.
But since then my HDMI port doesn't work anymore. You have any guesses what it could be? Or how it can be fixed?

I am using the MacBookPro13,3 I believe. You are using the MacBookPro13,2 in your config. 
And also do you have succesfull HDMI working?

**Comment by misa198** [comment]
Hi,
I am using MacBookPro13,2 config, with this configuration, HDMI is taken over by the iGPU. With the MacBookPro13,3 configuration, HDMI is taken over by the dGPU. Can you use dGPU with your configuration? I found [this thread](https://osxlatitude.com/forums/topic/10342-e5570-not-booting-high-sierra/), looks like R7 m370 must be disabled.

**Comment by job1234** [comment]
Thank you!
I have changed my SMBIOS from MacBookPro13,3 to MacBookPro13,2 and now my HDMI port is working again!
