### ISSUE TITLE
Brightness can patched via BRT6

### ISSUE THREAD

**Issue by quynkk1** [misa198/dell-latitude-e5570-hackintosh#5]
Can you try my BRT6 patched SSDT?
It's native via F11/F12, without using Karabiner Mapping Keyboard.
Rename in ACPI:
BRT6: 14204252 543602
XRT6: 14204252 545802
[SSDT-BRT6.aml.zip](https://github.com/misa198/dell-latitude-e5570-hackintosh/files/7740993/SSDT-BRT6.aml.zip)

**Comment by misa198** [comment]
Thank you!
