### ISSUE TITLE
HDMI Hot-plug problem

### ISSUE THREAD

**Issue by quynkk1** [misa198/dell-latitude-e5570-hackintosh#6]
I have tested your EFI but I got 1 problem.
When I plug HDMI cable, the screen went to black, and show up but very flirt (Up to 30fps).
I found that when I want to use HDMI, I need to sleep my laptop first, and wake and able to use HDMI again without flirt.
Any idea to fix this problem?

**Comment by misa198** [comment]
EFI của bạn hay của mình bị. Mình dùng 2 màn hình bình thường. Đạt 60fps. Ko gặp hiện tượng như bạn mô tả.

**Comment by misa198** [comment]
Mình test thử:
- Cắm hdmi trước khi bật máy
- Cắm/rút nóng lúc đang hoạt động
- Sleep rồi wake lại lúc đang cắm
Tất cả đều OK. 
Bạn thử reset nvram trước khi boot xem sao.

**Comment by quynkk1** [comment]
Để mình test :3
Ngoài ra sau khi sleep thì máy đôi lúc bị nháy màn hình. Bạn có cách fix không nhỉ?

**Comment by quynkk1** [comment]
Thêm nữa, bạn thử kext VoodooPS2 này hộ mình nhé, nguồn @SkyrilHD
Hỗ trợ gesture giống realmac.
https://github.com/SkyrilHD/VoodooPS2-ALPS/suites/4918461784/artifacts/141802957

**Comment by misa198** [comment]
Mình test thì nhận được touchpad rồi. Cảm ơn bạn. Trước tìm kext cho v8 mãi mà không thấy 😅
![Screen Shot 2022-01-14 at 16 38 20](https://user-images.githubusercontent.com/51451216/149494090-2f8fffd3-2e06-49db-b93c-a17966ed5b23.png)

**Comment by quynkk1** [comment]
Mình thử reset NVRAM rồi nhưng vẫn bị hiện tượng trên.
Sau khi sleep thì vẫn bị nháy màn.

**Comment by misa198** [comment]
Đây là máy mình lúc bật và sleep. Của mình hoạt động bình thường.
[Sleep](https://imgur.com/oBNBbL1)
[Cắm HDMI rồi bật máy](https://imgur.com/DcjuRN0)
