### ISSUE TITLE
Turbo boost not work

### ISSUE THREAD

**Issue by sonnguyen2000-github** [misa198/dell-latitude-e5570-hackintosh#8]
- Specs:

1. i7-6820HQ - Turbo Boost up to 3.6 GHz

- Description: Turbo boost không hoạt động, xung nhịp tối đa đạt đến 2.7 GHz. Tốc độ build app giảm rõ rệt so với Linux (có nhận turbo boost)

**Comment by misa198** [comment]
Bạn nói rõ hơn về cách test của bạn, nhiệt độ, hay có ảnh chụp màn hình không.

Mình dùng i5 6440HQ.Turbo Boost 4 cores được 3.0, 1 core được 3.5, đúng như mô tả của Intel. i5 6440HQ Dell giới hạn TDP ở 35W và trong lúc mình test thì máy vẫn nhận ăn được xấp xỉ công suất đó.

![Screen Shot 2022-01-20 at 21 01 34](https://user-images.githubusercontent.com/51451216/150353636-b0d86f7d-97be-46d5-afcb-6f56433259bb.png)

**Comment by sonnguyen2000-github** [comment]
ồ nay mình tải Intel Power Gadget về cũng test được turbo boost rồi. Hôm trước mình chỉ log từ sysctl ra thôi.
