### ISSUE TITLE
Is this repo ok for dell 5470 i7 6820hq

### ISSUE THREAD

**Issue by cricketget12** [misa198/dell-latitude-e5570-hackintosh#9]
Can i install this efi for 
Dell E5470  i7 6820hq
8gb ram
256gb m.2
Display 1080p

Like your hardware specs

**Comment by misa198** [comment]
Hello.
These 2 models have the same specs. But e5470 has 2 versions of touchpad. My EFI is for the ALPS touchpad version.
You can try it. If there is any touchpad error you can replace the VoodooPS2Controller kext with another kext.
Good luck.

https://dortania.github.io/OpenCore-Install-Guide/ktext.html#laptop-input

**Comment by cricketget12** [comment]
Ok thank you so much

**Comment by misa198** [comment]
Depending on the kext you use.

**Comment by misa198** [comment]
Looks like it's not a bug :))

https://osxdaily.com/2014/01/28/enable-tap-to-click-mac-trackpad/
